<?php


namespace Seegurke13\WebSocketBundle;


use Doctrine\Common\Annotations\AnnotationReader;
use Seegurke13\WebSocketBundle\DependencyInjection\WebsocketCompilerPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class Seegurke13WebSocketBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        $container->addCompilerPass(new WebsocketCompilerPass(new AnnotationReader()));
        parent::build($container); // TODO: Change the autogenerated stub
    }
}